update dev cd

diff --git a/.github/workflows/dev_cd.yaml b/.github/workflows/dev_cd.yaml
--- a/.github/workflows/dev_cd.yaml
+++ b/.github/workflows/dev_cd.yaml
@@ -3,46 +3,63 @@ name: Dev CD
 on:
   push:
     branches:
-      - "main"
+      - 'releases/**'
       # you may add other branches to
       # activate deployment for them, too.
 
 jobs:
-  get_commit_version:
+  check_semantic_tag_format:
     runs-on: ubuntu-latest
     outputs:
       # export to be used in other jobs
-      version: ${{ steps.get_commit_version.outputs.version }}
+      version: ${{ steps.check_semantic_tag_format.outputs.tag_name }}
       branch: ${{ steps.get_commit_version.outputs.branch }}
     steps:
       - uses: actions/checkout@v3
         name: Check out code
-        with:
-          # fetch the entire history
-          fetch-depth: 0
 
-      - id: get_commit_version
-        name: get commit version
+      - id: check_semantic_tag_format
+        name: Check tag format
         run: |
-          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-          if git describe --tags
-          then
-            VERSION="$(git describe --tags)-${BRANCH}"
+          TAG_NAME=$(git describe --tags --abbrev=0)
+          if [[ "$TAG_NAME" =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]]; then
+            echo "Tag format is valid"
           else
-            # fallback if no tag set yet:
-            COMMIT_HASH="$(git rev-parse --short HEAD)"
-            COMMIT_NUMBER="$(git rev-list --count HEAD)"
-            VERSION="0.0.0-${COMMIT_NUMBER}-${COMMIT_HASH}-${BRANCH}"
+            echo "Invalid tag format: $TAG_NAME"
+            exit 1
           fi
           # set as output:
-          echo "commit branch: ${BRANCH}"
-          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
-          echo "commit version: ${VERSION}"
-          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+          echo "commit branch: $BRANCH"
+          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
+          echo "tag name: $TAG_NAME"
+          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT
+
+  check_python_package_version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python environment
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.x'
+
+      - name: Check package version matches tag
+        run: |
+          PACKAGE_VERSION=$(python setup.py --version)
+          TAG_NAME=$(git describe --tags --abbrev=0)
+          if [[ "$PACKAGE_VERSION" == "$TAG_NAME" ]]; then
+            echo "Package version matches tag"
+          else
+            echo "Package version $PACKAGE_VERSION does not match tag $TAG_NAME"
+            exit 1
+          fi
 
   push_to_docker_hub:
     runs-on: ubuntu-latest
-    needs: get_commit_version
+    needs: check_semantic_tag_format
     steps:
       - uses: actions/checkout@v3
         name: Check out code
@@ -65,12 +82,12 @@ jobs:
         with:
           push: true
           #       platforms: linux/amd64,linux/arm64/v8
-          tags: "ghga/${{ github.event.repository.name }}:${{ needs.get_commit_version.outputs.version }},ghga/${{ github.event.repository.name }}:${{ needs.get_commit_version.outputs.branch }}"
+          tags: "ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.version }},ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.branch }}"
 
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@master
         with:
-          image-ref: "docker.io/ghga/${{ github.event.repository.name }}:${{ needs.get_commit_version.outputs.version }}"
+          image-ref: "docker.io/ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.version }}"
           format: "table"
           exit-code: "1"
           ignore-unfixed: true
@@ -85,7 +102,7 @@ jobs:
   # update_deployment_repo:
   #   runs-on: ubuntu-latest
   #   needs:
-  #     - get_commit_version
+  #     - check_semantic_tag_format
   #     - push_to_docker_hub
   #   env:
   #     DEPLOYMENT_CONFIG_REPO: ghga-de/helm
@@ -102,7 +119,7 @@ jobs:
   #             "client_payload": {
   #               "deploy_filename": "${{ github.event.repository.name }}",
   #               "app_name": "${{ github.event.repository.name }}",
-  #               "context": "${{ needs.get_commit_version.outputs.branch }}",
-  #               "new_image_tag": "${{ needs.get_commit_version.outputs.version }}"
+  #               "context": "${{ needs.check_semantic_tag_format.outputs.branch }}",
+  #               "new_image_tag": "${{ needs.check_semantic_tag_format.outputs.version }}"
   #             }
   #           }'
